try fixing entry point
abhi1693/setup-browser pull request #19
Opened 2022-08-10 20:56 UTC by esudaley

I was receiving File not found: '/home/runner/work/_actions/abhi1693/setup-browser/v0.3.1/index.js'
Changing the path to dist/index.js seems to have fixed the problem. 

Thank you for you work on this action!

2022-08-10 22:45 UTC, abhi1693 approved these changes

2022-08-10 22:47 UTC, abhi1693 requested changes
It seems like there are errors in the CI run for your change

2022-08-11 01:07 UTC, esudaley commented
Sorry about that, I'm seeing now that it was a naive approach. Attached is a screenshot of the original error message. 
I simply switched the entry point to dist/index.js and it's been working for me. My guess is that somewhere in the build/package step it's setting the path to dist/dist/index.js as seen in the second screenshot.

![ci_error](https://user-images.githubusercontent.com/51211969/184048223-e581c910-c033-4970-bc2e-f220cf8b5607.png)

![error_message](https://user-images.githubusercontent.com/51211969/184047879-9127a8ff-9fd0-415a-8e0e-d4fc03f7f22d.png)

2022-08-19 08:53 UTC, abhi1693 commented
@esudaley Try with `v0.3.2` in your workflow

2022-12-01 20:22 UTC, closed without merging